/**
 * Core X402 type definitions
 *
 * All types are designed to be config-driven with NO defaults.
 */

import type { Address, Hex, Hash } from "viem";

/**
 * X402 Payment identifier
 */
export type PaymentId = Hex;

/**
 * Transaction hash
 */
export type TransactionHash = Hash;

/**
 * Payment status enum
 */
export enum PaymentStatus {
  PENDING = "PENDING",
  CLAIMED = "CLAIMED",
  REFUNDED = "REFUNDED",
  EXPIRED = "EXPIRED",
}

/**
 * Service type for robot control
 */
export type ServiceType = "robot-control" | "custom";

/**
 * X402 Configuration (all values must be provided - NO defaults)
 */
export interface X402Config {
  /** RPC URL for blockchain connection */
  rpcUrl: string;
  /** Chain ID */
  chainId: number;
  /** QUSD Token contract address */
  tokenAddress: Address;
  /** Escrow contract address */
  escrowAddress: Address;
}

/**
 * Payment record from blockchain (matches Escrow.sol Payment struct)
 */
export interface PaymentRecord {
  /** Payment payer address */
  payer: Address;
  /** Payment recipient address */
  recipient: Address;
  /** Payment amount in wei */
  amount: bigint;
  /** Expiration timestamp (Unix seconds) */
  expiresAt: bigint;
  /** Whether payment has been claimed */
  claimed: boolean;
  /** Whether payment has been refunded */
  refunded: boolean;
}

/**
 * X402 Payment with computed status
 */
export interface X402Payment extends PaymentRecord {
  /** Payment identifier */
  id: PaymentId;
  /** Computed payment status */
  status: PaymentStatus;
}

/**
 * Payment request parameters for creating a payment
 */
export interface PaymentRequest {
  /** Unique payment identifier (generated by client) */
  paymentId: PaymentId;
  /** Recipient address who will receive the payment */
  recipient: Address;
  /** Payment amount in wei */
  amount: bigint;
  /** Duration in seconds until payment expires */
  duration: number;
  /** Optional service type */
  serviceType?: ServiceType;
  /** Optional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Payment response after successful creation
 */
export interface PaymentResponse {
  /** Payment identifier */
  paymentId: PaymentId;
  /** Transaction hash of payment creation */
  transactionHash: TransactionHash;
  /** Full payment details */
  payment: X402Payment;
}

/**
 * Payment claim response
 */
export interface ClaimResponse {
  /** Payment identifier */
  paymentId: PaymentId;
  /** Transaction hash of claim */
  transactionHash: TransactionHash;
  /** Updated payment details */
  payment: X402Payment;
}

/**
 * Payment refund response
 */
export interface RefundResponse {
  /** Payment identifier */
  paymentId: PaymentId;
  /** Transaction hash of refund */
  transactionHash: TransactionHash;
  /** Updated payment details */
  payment: X402Payment;
}
